[SEDONA-15] Add ST_MinimumBoundingRadius and ST_MinimumBoundingCircle functions
apache/incubator-sedona pull request #507
Opened 2021-02-04 14:06 UTC by michaelmerg

## Is this PR related to a proposed Issue?
https://issues.apache.org/jira/browse/SEDONA-15

## What changes were proposed in this PR?
Add the new geometry processing functions:
- ST_MinimumBoundingRadius
- ST_MinimumBoundingCircle

## How was this patch tested?
See unit tests

## Did this PR include necessary documentation updates?
Yes

2021-02-05 06:22 UTC, jiayuasu commented on docs/api/sql/GeoSparkSQL-Function.md
> +Since: `v1.?.?`
Please put Since: `1.0.1` here.

2021-02-05 06:24 UTC, jiayuasu requested changes
Thanks for your contribution! Can you please add some test cases for the two new functions?

You can add your test cases here: https://github.com/apache/incubator-sedona/blob/master/sql/src/test/scala/org/apache/sedona/sql/functionTestScala.scala#L852

2021-02-05 07:23 UTC, michaelmerg commented on docs/api/sql/GeoSparkSQL-Function.md
> +Since: `v1.?.?`
Updated

2021-02-05 07:26 UTC, michaelmerg commented
Sorry, forgot to commit the test cases. 
I'm not 100% happy with the `ST_MinimumBoundingCircle` test case because of the odd numbers when comparing the strings. Do you have any suggestions to improve of make it more robust?

2021-02-06 08:57 UTC, jiayuasu commented
@michaelmerg To make it robust, since ST_ functions internally call JTS functions, so probably you can call JTS function to validate the result in the test, instead of hard-coding the test result? What do you think?

2021-02-09 08:12 UTC, michaelmerg commented
@jiayuasu Yes, that's a good idea. I updated the test case.
Is there anything else that I need to do before we can merge this PR?

2021-02-09 08:25 UTC, jiayuasu approved these changes

2021-02-09 08:25 UTC, jiayuasu commented
@michaelmerg Thank you very much for the contribution!

2021-02-09 08:25 UTC, merged